curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/list'
###

curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/start/8683'
###

curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/status/8683'
###

curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/dump/8683/5'
###

curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/stop/8683/5'
###